version: "3.9"
services:
  rpg:
    build: .
    container_name: my_rpg
    privileged: true
    environment:
      DISPLAY: $DISPLAY
    network_mode:
      host
    volumes:
      - /tmp/.X11-unix:/tmp/.X11-unix
